options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'

substitutions:
  _REGION: us-central1

steps:
  # Build the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'NEXT_PUBLIC_API_URL=https://kabaddi-guru-backend-5uvrtavjca-uc.a.run.app',
      '-t', 'gcr.io/$PROJECT_ID/kabaddi-frontend:$SHORT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/kabaddi-frontend:latest',
      '.'
    ]
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kabaddi-frontend:$SHORT_SHA']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kabaddi-frontend:latest']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run',
      'deploy',
      'kabaddi-frontend',
      '--image', 'gcr.io/$PROJECT_ID/kabaddi-frontend:$SHORT_SHA',
      '--region', '$_REGION',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '3000',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--set-env-vars', 'NODE_ENV=production'
    ]

images:
  - 'gcr.io/$PROJECT_ID/kabaddi-frontend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/kabaddi-frontend:latest'
